name: Scheduled Empty Commit

on:
  schedule:
    - cron: '0 */10 * * *'  # Every 10 hours
  workflow_dispatch:         # Allow manual triggers

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Critical for write access

      - name: Create empty commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Scheduled empty commit [skip ci]"
          git push origin HEAD:main  # Explicitly push to 'main' branch
